services:
  mysql:
    image: mysql:8.0
    container_name: bom_media_api_mysql
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --max_allowed_packet=256M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: video_share_cms_dev
      MYSQL_USER: video_share_user
      MYSQL_PASSWORD: video_share_password
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"
    volumes:
      - bom_media_api_mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-uroot",
          "-proot_password",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  bom_media_api_mysql_data:
