export const MARIADB_COLLATION_PROBE_DISABLED = "DISABLED" as const;
export const MARIADB_COLLATION_PROBE_CONFIRMATION =
  "I_UNDERSTAND_THIS_ONLY_READS_SESSION_METADATA" as const;

export type MariaDbCollationProbeMode =
  | typeof MARIADB_COLLATION_PROBE_DISABLED
  | typeof MARIADB_COLLATION_PROBE_CONFIRMATION;

export const MARIADB_COLLATION_PROBE_EVENT =
  "MARIADB_COLLATION_PROBE_RESULT" as const;
