-- AlterTable
ALTER TABLE `VideoAsset` ADD COLUMN `embedAllow` VARCHAR(255) NULL,
    ADD COLUMN `embedCloudName` VARCHAR(120) NULL,
    ADD COLUMN `embedProvider` ENUM('CLOUDINARY_PLAYER', 'YOUTUBE', 'YOUTUBE_NOCOOKIE', 'VIMEO', 'GENERIC_IFRAME') NULL,
    ADD COLUMN `embedPublicId` VARCHAR(512) NULL,
    ADD COLUMN `sourceType` ENUM('UPLOAD', 'DIRECT_URL', 'EMBED') NOT NULL DEFAULT 'DIRECT_URL';
